export interface IProduct {
  id: number;
  imageUrl: string;
  name: string;
  url: string;
  autogeneratedSlug: string;
  description: string;
  price: number;
}

export type TProduct = Omit<
  IProduct,
  "url" | "autogeneratedSlug" | "description"
> & {
  quantity: number;
};
